image:
  repository: mysql
  tag: "5.7"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
deployment:
  name: mysql-db-deployment
  labels:
    app: mysql-db

